spring:
  profiles:
    active: 
    - dev
---
server: 
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
eurkea:
  client:
    service-url:
      defaultZone: http://eurkea-dev.com/7001/eurkea/
---

server: 
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
eurkea:
  client:
    service-url:
      defaultZone: http://eurkea-test.com/7001/eurkea/
